# Tools for Data Science Week 4 Peer Graded Assignment

## Introduction
Below, we will discuss some tools that Data Scientists use.

### Programming Languages of Data Science
<b>Below is the top 11 languages progamming languages used by Data Scientists</b> 
1. Python
2. SQL
3. R
4. Julia
5. JavaScript
6. Scala
7. Java
8. Go
9. Matlab
10. C/C++
11. Statistical Analytical Systems

<b>The following is a list of Data Science Libraries</b>
<em>
1. TensorFlow
1. NumPy
1. SciPy
1. Pandas
1. Matplotlib
1. Keras
1. SciKit-Learn
1. PyTorch </em>

#### Below is a list of Data Science Tools
--- <i>Apache Spark</i>
--- <i>IBM SPSS</i>
--- <i>Julia</i>
--- <i>Jupyter notebooks</i>
--- <i>Keras</i>

#### Aritmetic operators like +, -, *, and / can be used in code cells

In [7]:
(3*8*(7-2))^3

123

In [ ]:
In this example the first operation is the subtraction 7-2 is performed, then the multiplcation is performed, and finally the results is cubed.

We can also do conversions by dividing or multiplying by the conversion factor. 
As in the example below were we convert minutes to hours.

In [9]:
150/60

2.5

In this example we converted 150 minutes to hours.

#### Objective
- My objective is to learn who to capture and analyze bigdata to help my employers make decisions.

# Hans W. Hiser